version: '3'

services:

  django:
    build:
      context: backend
    depends_on:
      - postgres
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - STATIC_ROOT=${STATIC_ROOT}
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend/src/:/django/src
      - ./data/static/:/www/static

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/static/:/www/static
    depends_on:
      - django
