version: '3'

services:

  django:
    build:
      context: backend
      args:
        - DEPLOYMENT_ENVIRONMENT=${DEPLOYMENT_ENVIRONMENT}
    depends_on:
      - postgres
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=project.settings.${DEPLOYMENT_ENVIRONMENT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - STATIC_ROOT=${STATIC_ROOT}
    volumes:
      - ./backend/src/:/django/src
      - ./data/static/:${STATIC_ROOT}

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/static/:/www/static
    depends_on:
      - django
