x-postgres-environment: &postgres-env
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}

x-django-environment: &django-env
  <<: *postgres-env
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DJANGO_SETTINGS_MODULE: config.settings.${DEPLOYMENT_ENVIRONMENT}
  STATIC_ROOT: ${STATIC_ROOT}
  MEDIA_ROOT: ${MEDIA_ROOT}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  TMDB_API_KEY: ${TMDB_API_KEY}
  TMDB_READ_ACCESS_TOKEN: ${TMDB_READ_ACCESS_TOKEN}

x-django-service: &django-service
  build:
    context: backend
    args:
      - DEPLOYMENT_ENVIRONMENT=${DEPLOYMENT_ENVIRONMENT}
  environment:
      <<: *django-env
  volumes:
      - ./backend/src/:/app/src
      - django_static:${STATIC_ROOT}
      - django_media:${MEDIA_ROOT}
  depends_on:
    - postgres
    - redis

services:
  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - django
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build/:/static
      - django_static:/www/static
      - django_media:/www/media

  django:
    <<: *django-service

  celery:
    command: celery -A config worker -l info --concurrency=4
    <<: *django-service

  celery_beat:
    command: celery -A config beat -l info
    <<: *django-service

  celery_flower:
    command: celery -A config flower --port=5555
    <<: *django-service
    ports:
      - "5555:5555"
    profiles:
      - flower

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      <<: *postgres-env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  django_static:
  django_media:
  postgres_data:
