version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - '0.0.0.0:80:80'
    depends_on:
      - django
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build/:/static
      - ./data/static/:/www/static
      - ./data/media/:/www/media

  django:
    build:
      context: backend
      args:
        - DEPLOYMENT_ENVIRONMENT=${DEPLOYMENT_ENVIRONMENT}
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=project.settings.${DEPLOYMENT_ENVIRONMENT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - STATIC_ROOT=${STATIC_ROOT}
      - MEDIA_ROOT=${MEDIA_ROOT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    volumes:
      - ./backend/src/:/django/src
      - ./data/static/:${STATIC_ROOT}
      - ./data/media/:${MEDIA_ROOT}

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data
