# Generated by Django 5.2 on 2025-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmdbSyncRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('historic', 'Historic'), ('daily', 'Daily')], max_length=255, unique=True)),
                ('last_synced_release_date', models.DateField()),
            ],
        ),
    ]
