# Generated by Django 3.1.4 on 2021-02-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('duration', models.DurationField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('rating', models.CharField(blank=True, choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('12A', '12A'), ('15', '15'), ('18', '18')], max_length=3)),
            ],
        ),
    ]
