# Generated by Django 3.2.6 on 2025-04-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('release_date', models.DateField()),
                ('duration', models.DurationField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('rating', models.CharField(blank=True, choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('12A', '12A'), ('15', '15'), ('18', '18')], max_length=3)),
            ],
        ),
    ]
