# Generated by Django 5.2 on 2025-05-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "U"),
                    ("PG", "PG"),
                    ("12", "12"),
                    ("12A", "12A"),
                    ("15", "15"),
                    ("18", "18"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
