# Generated by Django 5.2 on 2025-05-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_make_more_fields_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="original_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="has_synced_with_tmdb",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="film",
            name="tmdb_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
