# Generated by Django 5.2 on 2025-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_tmdb_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
